apiVersion: v1
kind: Service
metadata:
    name: "systan-d700"
    labels:
        app: "systan-d700"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "systan-d700"